---
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: cilium 
servers: 1
agents: 2
image: docker.io/rancher/k3s:v1.27.4-k3s1
kubeAPI:
  host: k3d-cilium-serverlb
  hostPort: "6443"
network: k3d-network

ports:
  - port: 80:80 # same as `--port '8080:80@loadbalancer'`
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer

options:
  k3s:
    extraArgs:
      - arg: --tls-san=k3d-cilium-serverlb
        nodeFilters:
          - server:*
      - arg: --disable-network-policy
        nodeFilters:
          - server:*
      - arg: --flannel-backend=none
        nodeFilters:
          - server:*
      - arg: --disable-kube-proxy
        nodeFilters:
          - server:*
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --disable=servicelb
        nodeFilters:
          - server:*